# Generated by Django 5.1.2 on 2024-11-07 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('TEMPERATURA', 'Temperatura'), ('UMIDADE', 'Umidade'), ('LUMINOSIDADE', 'Luminosidad'), ('CONTADOR', 'Contador')], max_length=20)),
                ('unidade_medida', models.CharField(blank=True, max_length=20, null=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('localizacao', models.CharField(max_length=100)),
                ('responsavel', models.CharField(max_length=100)),
                ('status_operacional', models.BooleanField(default=True)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('mac_address', models.CharField(max_length=20, null=True)),
            ],
        ),
    ]
