# Generated by Django 5.1.2 on 2024-11-07 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartcity', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='tipo',
            field=models.CharField(choices=[('Temperatura', 'Temperatura'), ('Umidade', 'Umidade'), ('Luminosidade', 'Luminosidade'), ('Contador', 'Contador')], max_length=20),
        ),
    ]
