# Generated by Django 5.1.2 on 2024-11-26 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartcity', '0003_contadordata_luminosidadedata_temperaturadata_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_type', models.CharField(choices=[('Temperatura', 'Temperatura'), ('Umidade', 'Umidade'), ('Luminosidade', 'Luminosidade'), ('Contador', 'Contador')], max_length=20)),
                ('csv_file', models.FileField(upload_to='uploads/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
