# Generated by Django 5.1.2 on 2024-11-28 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smartcity', '0004_sensorupload'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contadordata',
            old_name='sensor_id',
            new_name='sensor',
        ),
        migrations.RenameField(
            model_name='luminosidadedata',
            old_name='sensor_id',
            new_name='sensor',
        ),
        migrations.RenameField(
            model_name='temperaturadata',
            old_name='sensor_id',
            new_name='sensor',
        ),
        migrations.RenameField(
            model_name='umidadedata',
            old_name='sensor_id',
            new_name='sensor',
        ),
    ]
